server:
  port: 8083

dubbo:
  application:
    name: dubbo-provider
  registry:
    # 注册中心  multicast不推荐
    #address: multicast://224.5.6.7:1234
    # 单机
    #address: zookeeper://123.56.169.57:2181
    # 集群
    address: zookeeper://192.168.61.128:2181?backup=192.168.61.129:2181,192.168.61.130:2181
    timeout: 6000
  # 元数据中心  生产者的一些配置  只有自己用，不需要注册到注册中心
  metadata-report:
    address: zookeeper://192.168.61.128:2181?backup=192.168.61.129:2181,192.168.61.130:2181
  protocol:
    name: dubbo
    port: 20880
  scan:
    base-packages: com/weimin/dubboprovider/service